# Generated by Django 5.0.7 on 2025-07-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
